export const ImgCategory = [
    { English: "Abstract", Bengali: "অ্যাবস্ট্রাক্ট" },
    { English: "Aerial", Bengali: "এয়ারিয়াল" },
    { English: "Animals", Bengali: "প্রাণী" },
    { English: "Architecture", Bengali: "স্থাপত্য" },
    { English: "Astrophotography", Bengali: "খগোল ফটোগ্রাফি" },
    { English: "Automotive", Bengali: "অটোমোটিভ" },
    { English: "Baby", Bengali: "শিশু" },
    { English: "Black and White", Bengali: "সাদা-কালো" },
    { English: "Boudoir", Bengali: "বউডোয়ার" },
    { English: "Business", Bengali: "ব্যবসা" },

    { English: "Beach", Bengali: "সৈকত" },

    { English: "Cat", Bengali: "বিড়াল" },
    { English: "Candid", Bengali: "ক্যান্ডিড" },
    { English: "Cityscape", Bengali: "শহরের দৃশ্য" },
    { English: "Commercial", Bengali: "বাণিজ্যিক" },
    { English: "Conceptual", Bengali: "ধারণাগত" },
    { English: "Concert", Bengali: "কনসার্ট" },
    { English: "Cultural", Bengali: "সাংস্কৃতিক" },
    { English: "Dance", Bengali: "নৃত্য" },
    { English: "Documentary", Bengali: "ডকুমেন্টারি" },
    { English: "Drone", Bengali: "ড্রোন" },
    { English: "Editorial", Bengali: "সম্পাদনা" },
    { English: "Event", Bengali: "ইভেন্ট" },
    { English: "Family", Bengali: "পরিবার" },
    { English: "Fashion", Bengali: "ফ্যাশন" },
    { English: "Festival", Bengali: "উৎসব" },
    { English: "Film Photography", Bengali: "ফিল্ম ফটোগ্রাফি" },
    { English: "Floral", Bengali: "ফুল" },
    { English: "Flower", Bengali: "ফুল" },
    { English: "Fine Art", Bengali: "ফাইন আর্ট" },
    { English: "Fireworks", Bengali: "আতশবাজি" },
    { English: "Fitness", Bengali: "ফিটনেস" },
    { English: "Fruit", Bengali: "ফল" },
    { English: "Furniture", Bengali: "ফার্নিচার" },
    { English: "Food", Bengali: "খাবার" },
    { English: "Forests", Bengali: "বন" },
    { English: "Glamour", Bengali: "গ্ল্যামার" },
    { English: "Golden Hour", Bengali: "গোল্ডেন আওয়ার" },
    { English: "Headshots", Bengali: "হেডশট" },
    { English: "Historic", Bengali: "ঐতিহাসিক" },
    { English: "Hiking", Bengali: "হাইকিং" },
    { English: "Holiday", Bengali: "ছুটি" },
    { English: "Industrial", Bengali: "শিল্প" },
    { English: "Infrared", Bengali: "ইনফ্রারেড" },
    { English: "Interior", Bengali: "অভ্যন্তরীণ" },
    { English: "Jewelry", Bengali: "গহনা" },
    { English: "Journalism", Bengali: "সাংবাদিকতা" },
    { English: "Landscapes", Bengali: "দৃশ্যপট" },
    { English: "Lifestyle", Bengali: "লাইফস্টাইল" },
    { English: "Long Exposure", Bengali: "দীর্ঘ এক্সপোজার" },
    { English: "Macro", Bengali: "ম্যাক্রো" },
    { English: "Medical", Bengali: "চিকিৎসা" },
    { English: "Minimalist", Bengali: "মিনিমালিস্ট" },
    { English: "Mirror Photography", Bengali: "আয়না ফটোগ্রাফি" },
    { English: "Misty", Bengali: "কুয়াশাচ্ছন্ন" },
    { English: "Mountains", Bengali: "পর্বত" },
    { English: "Music", Bengali: "সঙ্গীত" }, { English: "Mango", Bengali: "আম" },

    { English: "Nature", Bengali: "প্রকৃতি" },
    { English: "Neon Lights", Bengali: "নিয়ন লাইট" },
    { English: "Newborn", Bengali: "নবজাতক" },
    { English: "Night", Bengali: "রাত্রিকালীন" },
    { English: "Ocean", Bengali: "সমুদ্র" },
    { English: "Panoramic", Bengali: "প্যানোরামিক" },
    { English: "Patterns", Bengali: "প্যাটার্ন" },
    { English: "Pet", Bengali: "পোষা প্রাণী" },
    { English: "Photojournalism", Bengali: "ফটোজার্নালিজম" },
    { English: "Portrait", Bengali: "পোর্ট্রেট" },
    { English: "Product", Bengali: "প্রোডাক্ট ফটোগ্রাফি" },
    { English: "Real Estate", Bengali: "রিয়েল এস্টেট" },
    { English: "Reflection", Bengali: "প্রতিফলন" },
    { English: "Religious", Bengali: "ধর্মীয়" },
    { English: "Romantic", Bengali: "রোমান্টিক" },
    { English: "Rural", Bengali: "গ্রামীণ" },
    { English: "River", Bengali: "নদী" },
    { English: "Science", Bengali: "বিজ্ঞান" },
    { English: "Seasons", Bengali: "ঋতু" },
    { English: "Self-Portrait", Bengali: "সেলফ-পোর্ট্রেট" },
    { English: "Silhouette", Bengali: "সিলুয়েট" },
    { English: "Sky", Bengali: "আকাশ" },
    { English: "Social Media", Bengali: "সোশ্যাল মিডিয়া" },
    { English: "Space", Bengali: "মহাকাশ" },
    { English: "Sports", Bengali: "খেলাধুলা" },
    { English: "Still Life", Bengali: "স্থির জীবন" },
    { English: "Stock Photography", Bengali: "স্টক ফটোগ্রাফি" },
    { English: " Street Photography", Bengali: "স্ট্রিট ফটোগ্রাফি" },
    { English: "Studio", Bengali: "স্টুডিও" },
    { English: "Sunrise", Bengali: "সূর্যোদয়" },
    { English: "Sunset", Bengali: "সূর্যাস্ত" },
    { English: "Surreal", Bengali: "অতিপ্রাকৃত" },
    { English: "Technology", Bengali: "প্রযুক্তি" },
    { English: "Textures", Bengali: "টেক্সচার" },
    { English: "Theater", Bengali: "থিয়েটার" },
    { English: "Time-Lapse", Bengali: "টাইম-ল্যাপ্স" },
    { English: "Traditional", Bengali: "ঐতিহ্যবাহী" },
    { English: "Transportation", Bengali: "পরিবহন" },
    { English: "Travel", Bengali: "ভ্রমণ" },

    { English: "Underwater", Bengali: "জলের নিচে" },
    { English: "Urban", Bengali: "নগর" },
    { English: "Vintage", Bengali: "ভিনটেজ" },
    { English: "War", Bengali: "যুদ্ধ" },
    { English: "Wedding", Bengali: "বিবাহ" },
    { English: "Wildlife", Bengali: "বন্যপ্রাণী" },
    { English: "Winter", Bengali: "শীতকালীন" },
    { English: "X-Ray Photography", Bengali: "এক্স-রে ফটোগ্রাফি" },
    { English: "Zen Photography", Bengali: "জেন ফটোগ্রাফি" },

    { English: "Adventure", Bengali: "অ্যাডভেঞ্চার" },
    { English: "Animal Portraits", Bengali: "প্রাণী পোর্ট্রেট" },
    { English: "Classic", Bengali: "ক্লাসিক" },
    { English: "Cinematic", Bengali: "সিনেমাটিক" },
    { English: "Coastal", Bengali: "তটীয়" },
    { English: "Creative", Bengali: "সৃজনশীল" },
    { English: "Editorial Fashion", Bengali: "সম্পাদনা ফ্যাশন" },
    { English: "Environmental", Bengali: "পরিবেশগত" },
    { English: "Fine Art Portraits", Bengali: "ফাইন আর্ট পোর্ট্রেট" },
    { English: "Lifestyle Portraits", Bengali: "লাইফস্টাইল পোর্ট্রেট" },
    { English: "Real Life", Bengali: "প্রকৃত জীবন" },
    { English: "Timeless", Bengali: "অমর" },
    { English: "Urban Exploration", Bengali: "নগর অনুসন্ধান" }
];
